//
//  ColorRandomPresenter.swift
//  ColorGameTest
//
//  Created by Carolain Lenes Beltran on 19/07/21.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import Foundation
import UIKit

final class ColorRandomPresenter {

    
    // MARK: - Private properties -

    private unowned let view: ColorRandomViewInterface
    private let interactor: ColorRandomInteractorInterface
    private let wireframe: ColorRandomWireframeInterface

    // MARK: - Lifecycle -

    init(view: ColorRandomViewInterface, interactor: ColorRandomInteractorInterface, wireframe: ColorRandomWireframeInterface) {
        self.view = view
        self.interactor = interactor
        self.wireframe = wireframe
    }
}

// MARK: - Extensions -

extension ColorRandomPresenter: ColorRandomPresenterInterface {
    
    func getColorRandom(isPlayAgain: Bool){
        var colorArray: [UIColor] = []
        
        for _ in 1...12 {
            
            colorArray.append(isPlayAgain ? .random() : .darkGray)
        }
        
        self.view.reloadColorRandom(colorArray: colorArray)
    }
}
