//
//  ColorRandomInteractor.swift
//  ColorGameTest
//
//  Created by Carolain Lenes Beltran on 19/07/21.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import Foundation

final class ColorRandomInteractor {
}

// MARK: - Extensions -

extension ColorRandomInteractor: ColorRandomInteractorInterface {
}
