//
//  ColorRandomWireframe.swift
//  ColorGameTest
//
//  Created by Carolain Lenes Beltran on 19/07/21.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

final class ColorRandomWireframe: BaseWireframe {

    // MARK: - Private properties -

    private let storyboard = UIStoryboard(name: "ColorRandom", bundle: nil)

    // MARK: - Module setup -

    init() {
        let moduleViewController = storyboard.instantiateViewController(ofType: ColorRandomViewController.self)
        super.init(viewController: moduleViewController)

        let interactor = ColorRandomInteractor()
        let presenter = ColorRandomPresenter(view: moduleViewController, interactor: interactor, wireframe: self)
        moduleViewController.presenter = presenter
    }
    
    init(moduleViewController: ColorRandomViewController) {
        super.init(viewController: moduleViewController)

        let interactor = ColorRandomInteractor()
        let presenter = ColorRandomPresenter(view: moduleViewController, interactor: interactor, wireframe: self)
        moduleViewController.presenter = presenter
    }

}

// MARK: - Extensions -

extension ColorRandomWireframe: ColorRandomWireframeInterface {
}
